# Generated by Django 3.1 on 2020-11-13 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201113_1808'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='games_won_by_user1',
            new_name='games_won_by_player1',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='games_won_by_user2',
            new_name='games_won_by_player2',
        ),
    ]
