# Generated by Django 3.1 on 2020-11-16 05:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201113_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='round',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
    ]
